Fixed dummy runTest on functional test case.
In functional doc tests you can apparently have a test case that has
no runTest method.  Until now the Testing package added a dummy
runTest method in that case, and set it to None.

The previous commit added a functional test case.  Somehow this caused
a problem in an unknown other functional test case because the dummy
runTest method got called:

  Error in test runTest (Testing.ZopeTestCase.ZopeTestCase.FunctionalTestCase)
  Traceback (most recent call last):
    File ".../lib/python2.7/unittest/case.py", line 329, in run
      testMethod()
  TypeError: 'NoneType' object is not callable

It was not even caused by anything in the new tests: simply importing
was enough to trigger it:

  from Testing.ZopeTestCase import FunctionalTestCase

So this has something to do with the order in which tests are found.

I fixed it by making the dummy runTest method callable.