Improve testHTMLTests.py from Products.PageTemplates. (#1270)
* Improve testHTMLTests.py from Products.PageTemplates.

I was investigating a newer Chameleon 4.6.0, but ran into two errors on the current 4.4.4 as well.
Maybe this is just for me locally on Mac.

1. `test_module_traversal` could fail with:

```
  File "/Users/maurits/community/plone-coredev/6.2/src/Zope/src/Products/PageTemplates/ZRPythonExpr.py", line 49, in __call__
    return eval(self._code, vars, {})
   - __traceback_info__: a().getUser().getUserName()
  File "PythonExpr", line 1, in <module>
AttributeError: <exception str() failed>
```

Basically `getSecurityManager().getUser()` would return None instead of an anonymous user, so `None.getUserName` would give an AttributeError.
For the purposes of this test (check that access to `AccessControl.getSecurityManager` is allowed), just trying to call `getUser` is enough.

2. `test_underscore_traversal` could fail, or seem to fail.
A LocationError was raised, which should be fine because that is what we are testing for.
But really we were no longer testing anything useful.
In a old security fix we made sure that `random._itertools` could not be used.  But now I can't find a Python version where in a plain Python prompt `from random import _itertools` works.
So in this test I now recreate this situation.

* - manually fix linting; needs zope.meta run

* - ran zope.meta but removed testing for Python 3.14

---------

Co-authored-by: Jens Vagelpohl <jens@plyp.com>