Fix lockfile handling on Windows. Different exception:
...
  File "...\eggs\zope2-2.13.15-py2.7.egg\Zope2\Startup\run.py", line 72, in make_wsgi_app
    starter.prepare()
  File "...\eggs\zope2-2.13.15-py2.7.egg\Zope2\Startup\__init__.py", line 83, in prepare
    self.makeLockFile()
  File "...\eggs\zope2-2.13.15-py2.7.egg\Zope2\Startup\__init__.py", line 278, in makeLockFile
    os.unlink(lock_filename)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: '.../var/client1/client1.lock'